name: Deploy Job
run-name: Deploy ${{ github.event.inputs.branch }} to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to Deploy"
        required: true
        default: main
        type: string

      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This checks environment-scoped vars, secrets, and approvals
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set deployment stage
        run: |
          echo "STAGE=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Load environment variables dynamically
        shell: bash
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "Loading variables for $ENV"
          # Export to GitHub Actions environment
          echo "AWS_CLIENT_ID=${{ secrets.AWS_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AWS_CLIENT_SECRET=${{ secrets.AWS_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "FIRST_ENV=${{ vars.FIRST_ENV }}" >> $GITHUB_ENV
          echo "URL=${{ vars.URL }}" >> $GITHUB_ENV
          echo "STAGE=$ENV" >> $GITHUB_ENV

      - name: Print all environment variables
        run: printenv | sort
